Refactor merge fix
ThreadNews/threadnews-frontend pull request #43
Opened 2021-05-17 17:30 UTC by Jack-kelly-22

refactor and cleanup warnings

2021-05-17 18:09 UTC, akwong189 requested changes
there are local url references in a few files that may cause issues when deployed to heroku

2021-05-17 18:09 UTC, akwong189 commented on .vscode/settings.json
> +    "workbench.colorTheme": "Noctis Obscuro"
technically, we don't need this folder because it is someone's local settings

2021-05-17 18:09 UTC, akwong189 commented on src/ArticleCard.js
> +      axios.post("http://127.0.0.1:5000/view", data, head);
does this url need to access to the backend?

2021-05-17 18:09 UTC, akwong189 commented on src/ArticleCard.js
> +    axios.post("http://127.0.0.1:5000/comment", data, head).then((result) => {
same here

2021-05-17 18:09 UTC, akwong189 commented on src/CommentCol.js
>  CommentCol.defaultProps = {
static comments?

2021-05-17 18:09 UTC, akwong189 commented on src/EditProfile.js
> +      .post("http://127.0.0.1:5000/edit_profile", data, head)
using a local url, would this affect anything during deployment?

2021-05-17 18:09 UTC, akwong189 commented on src/FollowUserList.js
> +    axios.post("http://127.0.0.1:5000/follow_user",data,head);
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Login.js
> +      .post("http://127.0.0.1:5000/newUser", {
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Login.js
> +      .post("http://127.0.0.1:5000/login", { email: email, password: password })
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Profile.js
> +        axios.post('http://127.0.0.1:5000/articles',{article_ids:user.reposted_articles},head).then( result => {
local url

2021-05-17 18:09 UTC, akwong189 commented on src/SearchBar.js
> +        "http://127.0.0.1:5000/search_user",
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Social.js
> +  axios.post("http://127.0.0.1:5000/follow_user", data, head);
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Social.js
> +  axios.post("http://127.0.0.1:5000/users", data, head).then((result) => {
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Social.js
> +  axios.post("http://127.0.0.1:5000/repost", data, head);
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Social.js
> +  axios.post("http://127.0.0.1:5000/save", data, head);
local url

2021-05-17 18:09 UTC, akwong189 commented on src/Social.js
> +  axios.post("http://127.0.0.1:5000/like", data, head);
using local url

2021-05-17 18:09 UTC, akwong189 commented on src/ThreadPage.js
> +    axios.post("http://127.0.0.1:5000/threads", data, head).then((result) => {
using local url

2021-05-18 04:00 UTC, Jack-kelly-22 commented
updated urls

2021-05-18 04:01 UTC, akwong189 approved these changes
these 2 files look good

2021-05-18 04:06 UTC, akwong189 requested changes
mistakenly approved, still a few files with local urls

2021-05-18 04:07 UTC, akwong189 commented on src/Social.js
> +  axios.post("http://127.0.0.1:5000/users", data, head).then((result) => {
was fixed

2021-05-18 07:01 UTC, akwong189 approved these changes
All urls have been resolved

2021-05-19 01:46 UTC, merged